version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app
    command: flask run --host=0.0.0.0 --port=5000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures hot reload works in Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
