FROM python:3.11-slim

WORKDIR /app


COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . . 

CMD [ "python", "-m", "flask", "--app", "app:create_app", "run", "--host=0.0.0.0", "--port=5000" ]


