FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy source code later via volume
EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload" ]