name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./backend
        env:
          PYTHONPATH: .
        run: |
          pytest --maxfail=1 --disable-warnings -q

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install flake8
        run: pip install flake8
      - name: Run Python linter
        working-directory: ./backend
        run: flake8 .

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend, frontend, lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-backend:latest ./backend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-backend:${{ github.sha }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-frontend:latest ./frontend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nanolink-frontend:${{ github.sha }}
